services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:8081"
    env_file:
      - .env
    volumes:
      - logs-data:${LOG_PATH}
    environment:
      - ConnectionStrings__DefaultConnection=Server=${DB_HOST},${DB_PORT};Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=${STAGE}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - LOG_PATH=${LOG_PATH}/log.txt

volumes:
  logs-data:
