services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:8081"
    env_file:
      - .env
    volumes:
      - /c/Dany/Portafolio/v1/logs:/mnt/logs
    environment:
      - ConnectionStrings__DefaultConnection=Server=${DB_HOST},${DB_PORT};Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=${STAGE}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - LOG_PATH=${LOG_PATH}/log.txt
    networks:
      - sql_server_mi_red  # Usar la misma red para la comunicación con el contenedor SQL Server


networks:
  sql_server_mi_red:  # Usar el mismo nombre de red que en el otro docker-compose
    external: true  # Especificar que la red es interna y debe ser creada automáticamente